### ISSUE TITLE
Uncaught Error: Line 8: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by yarons** [vermotr/atom-jsfiddle#1]
[Enter steps to reproduce below:]
1. Clicked Packages
2. Clicked Start

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-jsfiddle](https://github.com/vermotr/atom-jsfiddle) package, v0.2.0
### Stack Trace

Uncaught Error: Line 8: Unexpected token ILLEGAL

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:5618

Error: Line 8: Unexpected token ILLEGAL
    at constructError (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:2406:21)
    at createError (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:2504:15)
    at scanPunctuator (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:842:13)
    at advance (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:1621:16)
    at collectToken (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:1634:17)
    at lex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:1690:61)
    at Object.tokenize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regexpu/node_modules/esprima/esprima.js:5600:21)
    at tokenize (/Users/yaronshahrabani/.atom/packages/atom-jsfiddle/node_modules/json-parser/index.js:10:22)
    at Object.parse (/Users/yaronshahrabani/.atom/packages/atom-jsfiddle/node_modules/json-parser/index.js:42:12)
    at Request._callback (/Users/yaronshahrabani/.atom/packages/atom-jsfiddle/lib/atom-jsfiddle.coffee:65:25)
    at Request.self.callback (/Users/yaronshahrabani/.atom/packages/atom-jsfiddle/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/yaronshahrabani/.atom/packages/atom-jsfiddle/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/yaronshahrabani/.atom/packages/atom-jsfiddle/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
  3x -2:43.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 atom-jsfiddle:start (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 atom-jsfiddle:upload (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-jsfiddle, v0.2.0
autocomplete-go, v1.1.0
builder-go, v1.0.0
emmet, v2.4.3
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
jquery-snippets, v11.0.0
language-markdown, v0.14.0
linter, v1.11.10
linter-shellcheck, v1.2.0
minimap, v4.24.6
navigator-godef, v1.0.3
pigments, v0.29.2
regex-railroad-diagram, v0.16.0
tester-go, v1.0.4
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by vermotr** [comment]
I will try to fix it
